name: test-job
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delta Files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          fileOutput: 'csv'

      - name: Display files' delta
        run: |
          cat $HOME/files.csv

      - name: prepare changed files
        run: python3 mv-files.py $HOME/files.csv

      - name: sync the files
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'files'
          target-directory: 'src/posts'
          user-email: 45619033+BirnadinErick@users.noreply.github.com
          target-branch: master
          destination-github-username: 'BirnadinErick'
          destination-repository-name: 'astro-test'

