name: test-job
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delta Files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Display files' delta
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json

      - name: sync-repo
        run: echo "syncing..."

